env:
  browser: false
  commonjs: true
  es2017: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
# parserOptions:
#   ecmaVersion: 11
rules:
  no-unused-vars: warn
  semi: warn
